# Generated by Django 5.2 on 2026-04-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
